# Generated by Django 3.2.5 on 2021-07-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='contetn',
            new_name='content',
        ),
    ]
