# Generated by Django 3.2.5 on 2021-08-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20210723_1302'),
        ('pybo', '0007_auto_20210726_1854'),
    ]

    operations = [
    ]
